import * as React from "react"
import type { ComboboxOption } from "@/components/ui/Combobox"
import { getFlagCdnUrl, getFlagCdnUrlByCode } from "@/lib/flagcdn"
import type { NationalityCard } from "./types"

export function getFlagUrl(countryName: string, isoCode?: string) {
  if (isoCode) return getFlagCdnUrlByCode(isoCode, 160)
  return getFlagCdnUrl(countryName, 160)
}

export const FEATURED_NATIONALITIES: NationalityCard[] = [
  {
    code: "gb",
    label: "United Kingdom",
    href: "/guide/visa-exemptions",
    flag: "🇬🇧",
    isPopular: true,
    group: "good",
  },
  {
    code: "us",
    label: "United States",
    href: "/guide/visa-exemptions",
    flag: "🇺🇸",
    isPopular: true,
    group: "good",
  },
  {
    code: "au",
    label: "Australia",
    href: "/guide/visa-exemptions",
    flag: "🇦🇺",
    isPopular: true,
    group: "good",
  },
  {
    code: "fr",
    label: "France",
    href: "/guide/visa-exemptions",
    flag: "🇫🇷",
    isPopular: true,
    group: "good",
  },
  {
    code: "ca",
    label: "Canada",
    href: "/guide/visa-exemptions",
    flag: "🇨🇦",
    group: "good",
  },
  {
    code: "de",
    label: "Germany",
    href: "/guide/visa-exemptions",
    flag: "🇩🇪",
    group: "good",
  },
  {
    code: "in",
    label: "India",
    href: "/guide/visa-exemptions",
    flag: "🇮🇳",
    group: "normal",
  },
  {
    code: "jp",
    label: "Japan",
    href: "/guide/visa-exemptions",
    flag: "🇯🇵",
    group: "good",
  },
]

export const EXTENDED_NATIONALITIES: NationalityCard[] = [
  {
    code: "vn",
    label: "Albania",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Algeria",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "American Samoa",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Andorra",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Antigua and Barbuda",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Argentina",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Armenia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Aruba",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Austria",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Azerbaijan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bahamas",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bahrain",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Belarus",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Belgium",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Belize",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bermuda",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bhutan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bolivia, Plurinational State of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bosnia and Herzegovina",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Botswana",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Brazil",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "British Indian Ocean Territory",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Brunei Darussalam",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Bulgaria",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Cambodia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Chad",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Chile",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "China",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Christmas Island",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Cocos (Keeling) Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Colombia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Cook Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Costa Rica",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Croatia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Cuba",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Curaçao",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Cyprus",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Czechia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Denmark",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Dominica",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Dominican Republic",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Ecuador",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Egypt",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "El Salvador",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Estonia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Fiji",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Finland",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Georgia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Greece",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Greenland",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Guam",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Guatemala",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Honduras",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "hk",
    label: "Hong Kong",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Hungary",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Iceland",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Indonesia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Ireland",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Israel",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Italy",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Jamaica",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Jersey",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Jordan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Kazakhstan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Kiribati",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Korea, Democratic People's Republic of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Korea, Republic of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Kuwait",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Kyrgyzstan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Lao People's Democratic Republic",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Latvia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Liechtenstein",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Lithuania",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Luxembourg",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Macao",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Malaysia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Maldives",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Mali",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Malta",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Mauritius",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Mexico",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Micronesia, Federated States of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Moldova, Republic of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Monaco",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Mongolia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Montenegro",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Montserrat",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Morocco",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Myanmar",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Nepal",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Netherlands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "New Caledonia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "nz",
    label: "New Zealand",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Nicaragua",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Norfolk Island",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "North Macedonia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Northern Mariana Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Norway",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Oman",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Palau",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Panama",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Paraguay",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Peru",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Philippines",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Pitcairn",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Poland",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Portugal",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Puerto Rico",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Qatar",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Romania",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Russian Federation",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "San Marino",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Sao Tome and Principe",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "sa",
    label: "Saudi Arabia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Serbia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Singapore",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Sint Maarten (Dutch part)",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Slovakia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Slovenia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Solomon Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Somalia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "za",
    label: "South Africa",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "South Georgia and the South Sandwich Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Spain",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "lk",
    label: "Sri Lanka",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Svalbard and Jan Mayen",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Sweden",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Switzerland",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Taiwan, Province of China",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Tajikistan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Thailand",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Timor-Leste",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Tunisia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Turkmenistan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Tuvalu",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Türkiye",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Ukraine",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "ae",
    label: "United Arab Emirates",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "United States Minor Outlying Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Uruguay",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Uzbekistan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Venezuela, Bolivarian Republic of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "good",
  },
  {
    code: "vn",
    label: "Angola",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Anguilla",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Antarctica",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Aruba",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Barbados",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Benin",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Bonaire, Sint Eustatius and Saba",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Bouvet Island",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Burkina Faso",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Burundi",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Cabo Verde",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Cayman Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Central African Republic",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Comoros",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Côte d'Ivoire",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Djibouti",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Equatorial Guinea",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Eritrea",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Eswatini",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Ethiopia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Falkland Islands (Malvinas)",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Faroe Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Gabon",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Gambia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Gibraltar",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Guernsey",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Guinea",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Guinea-Bissau",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Guyana",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Haiti",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Heard Island and McDonald Islands",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Holy See (Vatican City State)",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Kenya",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Lebanon",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Lesotho",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Liberia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Libya",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Madagascar",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Malawi",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Mozambique",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Namibia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Palestine, State of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Papua New Guinea",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Rwanda",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Samoa",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Senegal",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Seychelles",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Sierra Leone",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "South Sudan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Sudan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Suriname",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Tanzania, United Republic of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Togo",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Tokelau",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Tonga",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Trinidad and Tobago",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Uganda",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Zambia",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Zimbabwe",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "normal",
  },
  {
    code: "vn",
    label: "Afghanistan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Bangladesh",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Cameroon",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Congo",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Congo, The Democratic Republic of the",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Ghana",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Iran, Islamic Republic of",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Iraq",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Niger",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Nigeria",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Niue",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Pakistan",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Syrian Arab Republic",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Vanuatu",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
  {
    code: "vn",
    label: "Yemen",
    href: "/guide/visa-exemptions",
    flag: "",
    group: "blacklist",
  },
]

export const ALL_COUNTRIES_OPTIONS = [
  ...FEATURED_NATIONALITIES,
  ...EXTENDED_NATIONALITIES,
]

export const NATIONALITY_OPTIONS: ComboboxOption[] = (() => {
  const sorted = [...ALL_COUNTRIES_OPTIONS].sort((a, b) =>
    a.label.localeCompare(b.label)
  )
  const groups = new Map<string, typeof ALL_COUNTRIES_OPTIONS>()
  for (const c of sorted) {
    const letter = c.label[0].toUpperCase()
    if (!groups.has(letter)) groups.set(letter, [])
    groups.get(letter)!.push(c)
  }
  const result: ComboboxOption[] = []
  for (const [letter, items] of groups) {
    result.push({
      value: `__header_${letter}`,
      label: letter,
      isHeader: true,
    })
    for (const c of items) {
      result.push({
        value: c.code,
        label: c.label,
        icon: (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={getFlagUrl(c.label, c.code)}
            className="w-5 h-5 object-cover rounded-full border border-stone-200/50 shrink-0"
            alt=""
          />
        ),
      })
    }
  }
  return result
})()

export type ExemptionInfo = {
  status: "blacklist" | "exempt" | "evisa_only"
  exemptionDays: number
}

export function deriveExemptionInfo(group: string, exemptionDays: number): ExemptionInfo {
  if (group === "blacklist") return { status: "blacklist", exemptionDays: 0 }
  if (exemptionDays >= 1) return { status: "exempt", exemptionDays }
  return { status: "evisa_only", exemptionDays: 0 }
}
